# Generated by Django 2.2.16 on 2020-10-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='act',
            field=models.IntegerField(default=0),
        ),
    ]
