# Generated by Django 2.2.16 on 2020-10-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('abouttxt', models.TextField(default='')),
                ('fb', models.CharField(max_length=50)),
                ('tw', models.CharField(max_length=50)),
                ('yt', models.CharField(max_length=50)),
                ('tell', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
                ('set_name', models.CharField(max_length=50)),
                ('picurlbottom', models.TextField(default='-')),
                ('picbottom', models.TextField(default='-')),
                ('picurltop', models.TextField(default='-')),
                ('pictop', models.TextField(default='-')),
            ],
        ),
    ]
