# Generated by Django 2.2.16 on 2020-10-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20201013_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.CharField(default='', max_length=12),
        ),
    ]
