# Generated by Django 2.2.16 on 2020-10-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20201013_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(max_length=12),
        ),
    ]
